name: Nik's notes
permalink: /blog/:year/:month/:day/:title
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown

description: Nik's Notes
author:
  name: Nik Rahmel
  email: niklas@rahmel.eu
  github: niklasR
  twitter: niklasRen
  linkedin: niklasr
  bio: Young and keen graduate software engineer
  email_md5: de6247892bb3956d13c34a49785845ba

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Nik's Notes

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

gems:
  - jekyll-paginate
